/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2012 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

// NewPhysics specific product patches.
// This file is #included by hknpPatches.cpp

/* This file is TEMPORARY, it contains all patches needed to introduce
serializable new physics classes. This file will be split in several different
versions (one for each Havok release) once New Physics will be released. At that
stage all the patches will end up in the latest Havok version. */

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpShapeTagCodecType", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpCompressedMeshShapeTreeDataRunData", 0)
	HK_PATCH_MEMBER_ADDED("data", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpCollisionFilter", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("type", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpMxConstraint", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED_BYTE("constraintType", 2)
	HK_PATCH_MEMBER_ADDED("padding1", TYPE_TUPLE_BYTE, HK_NULL, 3)
	HK_PATCH_MEMBER_ADDED("bodyIdA", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("bodyIdB", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("motionIdA", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("motionIdB", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_REAL("impulseLimitA", 18446726481523507000.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("impulseLimitB", 18446726481523507000.000000f)
	HK_PATCH_MEMBER_ADDED("padding", TYPE_TUPLE_BYTE, HK_NULL, 4)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpAction", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("userData", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpMaterialCinfo", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpMaterial")
	HK_PATCH_DEPENDS("hknpMaterial", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpPairCollisionFilter", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpCollisionFilter")
	HK_PATCH_MEMBER_ADDED("childFilter", TYPE_OBJECT, "hknpCollisionFilter", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpCollisionFilter", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpCompressedMeshShape", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpCompositeShape")
	HK_PATCH_MEMBER_ADDED("internals", TYPE_STRUCT, "hknpCompressedMeshShapeTree", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeDynamicStorage5", 0)
	HK_PATCH_DEPENDS("hknpCompressedMeshShapeTree", 0)
	HK_PATCH_DEPENDS("hkcdStaticMeshTreeBase", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkcdStaticMeshTreehkcdStaticMeshTreeCommonConfigunsignedintunsignedlonglong1121hknpCompressedMeshShapeTreeDataRun", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeTreehkcdStaticTreeDynamicStorage5", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpShape", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis5", 0)
	HK_PATCH_DEPENDS("hknpCompositeShape", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpUnaryAction", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpAction")
	HK_PATCH_MEMBER_ADDED("body", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpAction", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpExternMeshShape", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpCompositeShape")
	HK_PATCH_MEMBER_ADDED("source", TYPE_OBJECT, "hknpExternMeshShapeISource", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpExternMeshShapeISource", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpShape", 0)
	HK_PATCH_DEPENDS("hknpCompositeShape", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpBody", 0)
	HK_PATCH_MEMBER_ADDED("transform", TYPE_VEC_16, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("aabbWithKey", TYPE_STRUCT, "hkAabb16", 0)
	HK_PATCH_MEMBER_ADDED("shape", TYPE_OBJECT, "hknpShape", 0)
	HK_PATCH_MEMBER_ADDED("collisionFilterInfo", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("materialId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("motionId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("qualityType", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("qualityFlags", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("bodyId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("flags", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("broadPhaseId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("nextAttachedBodyId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("radiusOfComCenteredBoundingSphere", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("maxTimDistance", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("timAngle", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("shapeSizeDiv16", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("indexIntoActiveListOrDeactivatedIslandId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("maxCollisionDistance", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("userData", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("motionToBodyRotation", TYPE_TUPLE_INT, HK_NULL, 4)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkAabb16", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpShape", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpSpringAction", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpBinaryAction")
	HK_PATCH_MEMBER_ADDED("lastForce", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("positionAinA", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("positionBinB", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_REAL("restLength", 1.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("strength", 1000.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("damping", 0.100000f)
	HK_PATCH_MEMBER_ADDED_BYTE("onCompression", 1)
	HK_PATCH_MEMBER_ADDED_BYTE("onExtension", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpAction", 0)
	HK_PATCH_DEPENDS("hknpBinaryAction", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkcdStaticMeshTreehkcdStaticMeshTreeCommonConfigunsignedintunsignedlonglong1121hknpCompressedMeshShapeTreeDataRun", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkcdStaticMeshTreeBase")
	HK_PATCH_MEMBER_ADDED("packedVertices", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("sharedVertices", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("primitiveDataRuns", TYPE_ARRAY_STRUCT, "hknpCompressedMeshShapeTreeDataRun", 0)
	HK_PATCH_DEPENDS("hknpCompressedMeshShapeTreeDataRun", 0)
	HK_PATCH_DEPENDS("hkcdStaticMeshTreeBasePrimitiveDataRunBasehknpCompressedMeshShapeTreeDataRunData", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeDynamicStorage5", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeTreehkcdStaticTreeDynamicStorage5", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis5", 0)
	HK_PATCH_DEPENDS("hkcdStaticMeshTreeBase", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpCentrifugalForceAction", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpUnaryAction")
	HK_PATCH_DEPENDS("hknpUnaryAction", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpAction", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpCompressedMeshShapeTree", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkcdStaticMeshTreehkcdStaticMeshTreeCommonConfigunsignedintunsignedlonglong1121hknpCompressedMeshShapeTreeDataRun")
	HK_PATCH_DEPENDS("hkcdStaticMeshTreehkcdStaticMeshTreeCommonConfigunsignedintunsignedlonglong1121hknpCompressedMeshShapeTreeDataRun", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeDynamicStorage5", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeTreehkcdStaticTreeDynamicStorage5", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis5", 0)
	HK_PATCH_DEPENDS("hkcdStaticMeshTreeBase", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpShapeType", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpMotion", 0)
	HK_PATCH_MEMBER_ADDED("centerOfMassInWorld", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("orientation", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("invInertia", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("density", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("toi", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("maxRotationToPreventTunneling", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("maxLinearAccelerationDistancePerStep", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("linearVelocityCage", TYPE_TUPLE_REAL, HK_NULL, 3)
	HK_PATCH_MEMBER_ADDED("firstAttachedBody", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("numAttachedBodies", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("motionPropertiesId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("solverId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isStaticOrKeyframed", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("cellIndex", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("linearVelocity", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("angularVelocity", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("appliedLinearVelocity", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("appliedAngularVelocity", TYPE_VEC_4, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpCollisionDispatchType", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpMotionCinfo", 0)
	HK_PATCH_MEMBER_ADDED("motionPropertiesId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_BYTE("enableDeactivation", 1)
	HK_PATCH_MEMBER_ADDED_REAL("invMass", 1.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("density", 1.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("maxLinearAccelerationDistancePerStep", 18446726481523507000.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("maxRotationToPreventTunneling", 18446726481523507000.000000f)
	HK_PATCH_MEMBER_ADDED("invInertiaLocal", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_VEC_4("centerOfMassWorld", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("orientation", 0.000000f,0.000000f,0.000000f,1.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("linearVelocity", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("angularVelocity", 0.000000f,0.000000f,0.000000f,0.000000f)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpMaterial", 0)
	HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("frictionCombinePolicy", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("dynamicFriction", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("staticFriction", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("rollingFriction", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("restitutionCombinePolicy", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("restitution", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("softContactForceFactor", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("softContactDampFactor", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("softContactSeperationVelocity", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("triggerVolumeAccuracy", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("massChangerCategory", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("weldingMethod", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("massChangerHeavyObjectFactor", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("weldingTolerance", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("disablingCollisionsBetweenCvxCvxDynamicObjectsDistance", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("maxContactImpulse", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("surfaceVelocity", TYPE_OBJECT, "hknpSurfaceVelocity", 0)
	HK_PATCH_MEMBER_ADDED("isUnique", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("flags", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isShared", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpSurfaceVelocity", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkcdStaticMeshTreeBasePrimitiveDataRunBasehknpCompressedMeshShapeTreeDataRunData", 0)
	HK_PATCH_MEMBER_ADDED("value", TYPE_STRUCT, "hknpCompressedMeshShapeTreeDataRunData", 0)
	HK_PATCH_MEMBER_ADDED("index", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("count", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hknpCompressedMeshShapeTreeDataRunData", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpCompoundShape", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpCompositeShape")
	HK_PATCH_MEMBER_ADDED("instances", TYPE_STRUCT, "hkFreeListArrayhknpShapeInstancehkHandleshort32767hknpShapeInstanceIdDiscriminant16hknpShapeInstance", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)	
	HK_PATCH_DEPENDS("hkFreeListArrayhknpShapeInstancehkHandleshort32767hknpShapeInstanceIdDiscriminant16hknpShapeInstance", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpShape", 0)
	HK_PATCH_DEPENDS("hknpCompositeShape", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpShapeTagCodec", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpBinaryAction", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpAction")
	HK_PATCH_MEMBER_ADDED("bodyA", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("bodyB", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpAction", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpPairCollisionFilterMapPairFilterKeyOverrideType", 0)
	HK_PATCH_MEMBER_ADDED("numElems", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("hashMod", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpDynamicCompoundShape", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpCompoundShape")
	HK_PATCH_MEMBER_ADDED("internals", TYPE_STRUCT, "hknpDynamicCompoundShapeTree", 0)
	HK_PATCH_DEPENDS("hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodec32", 0)
	HK_PATCH_DEPENDS("hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodec32", 0)
	HK_PATCH_DEPENDS("hkcdDynamicTreeTreehkcdDynamicTreeDynamicStorage16", 0)
	HK_PATCH_DEPENDS("hkcdDynamicTreeAnisotropicMetric", 0)
	HK_PATCH_DEPENDS("hknpCompoundShape", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkcdDynamicTreeDefaultTree32Storage", 0)
	HK_PATCH_DEPENDS("hknpDynamicCompoundShapeTree", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpShape", 0)
	HK_PATCH_DEPENDS("hkcdDynamicTreeDynamicStorage16", 0)
	HK_PATCH_DEPENDS("hknpCompositeShape", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpMinMaxQuadTreeMinMaxLevel", 0)
	HK_PATCH_MEMBER_ADDED("minMaxData", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("xRes", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("zRes", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpShape", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("type", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("dispatchType", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("bitsPerKey", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("shapeInfoCodecType", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("properties", TYPE_OBJECT, "hkRefCountedProperties", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkRefCountedProperties", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpShapeInstance", 0)
	HK_PATCH_MEMBER_ADDED("transform", TYPE_VEC_16, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("scale", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("shape", TYPE_OBJECT, "hknpShape", 0)
	HK_PATCH_MEMBER_ADDED("shapeInfo", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hknpShape", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpStaticCompoundShapeTree", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkcdStaticTreeDefaultTreeStorage6")
	HK_PATCH_DEPENDS("hkcdStaticTreeDefaultTreeStorage6", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeDynamicStorage6", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeTreehkcdStaticTreeDynamicStorage6", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis6", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpMotionProperties", 0)
	HK_PATCH_MEMBER_ADDED("linearDamping", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("angularDamping", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("maxLinearVelocity", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("maxAngularVelocity", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("gravityFactor", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_REAL("solverStabilizationVelocityThreshold", 1.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("solverStabilizationVelocityReduction", 0.000000f)
	HK_PATCH_MEMBER_ADDED("maxDistSqrd", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("maxRotSqrd", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("invBlockSize", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pathingUpperThreshold", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pathingLowerThreshold", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("numDeactivationFrequencyPasses", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("deactivationVelocityScaleSquare", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("minimumPathingVelocityScaleSquare", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("spikingVelocityScaleThresholdSquared", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("minimumSpikingVelocityScaleSquared", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpExternMeshShapeISource", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpBallSocketMxConstraint", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpMxConstraint")
	HK_PATCH_MEMBER_ADDED_VEC_4("localPivotA", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("localPivotB", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpMxConstraint", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpDynamicCompoundShapeTree", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkcdDynamicTreeDefaultTree32Storage")
	HK_PATCH_DEPENDS("hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodec32", 0)
	HK_PATCH_DEPENDS("hkcdDynamicTreeTreehkcdDynamicTreeDynamicStorage16", 0)
	HK_PATCH_DEPENDS("hkcdDynamicTreeDefaultTree32Storage", 0)
	HK_PATCH_DEPENDS("hkcdDynamicTreeAnisotropicMetric", 0)
	HK_PATCH_DEPENDS("hkcdDynamicTreeDynamicStorage16", 0)
	HK_PATCH_DEPENDS("hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodec32", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpBodyCinfo", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpBodyCinfoBase")
	HK_PATCH_MEMBER_ADDED("reservedBodyId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("position", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_VEC_4("orientation", 0.000000f,0.000000f,0.000000f,1.000000f)
	HK_PATCH_DEPENDS("hknpBodyCinfoBase", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpStaticCompoundShape", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpCompoundShape")
	HK_PATCH_MEMBER_ADDED("internals", TYPE_STRUCT, "hknpStaticCompoundShapeTree", 0)
	HK_PATCH_DEPENDS("hknpStaticCompoundShapeTree", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeDefaultTreeStorage6", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeDynamicStorage6", 0)
	HK_PATCH_DEPENDS("hknpCompoundShape", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpShape", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeTreehkcdStaticTreeDynamicStorage6", 0)
	HK_PATCH_DEPENDS("hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis6", 0)
	HK_PATCH_DEPENDS("hknpCompositeShape", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpRagdollMxConstraint", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpBallSocketMxConstraint")
	HK_PATCH_MEMBER_ADDED("transformA", TYPE_VEC_16, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("transformB", TYPE_VEC_16, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_REAL("planeMin", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("planeMax", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("twistMin", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("twistMax", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("coneMin", 0.000000f)
	HK_PATCH_MEMBER_ADDED("pad", TYPE_TUPLE_BYTE, HK_NULL, 12)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpMxConstraint", 0)
	HK_PATCH_DEPENDS("hknpBallSocketMxConstraint", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpCompositeShape", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpShape")	
	HK_PATCH_MEMBER_ADDED("materialPalette", TYPE_OBJECT, "hknpMaterialPalette", 0)
	HK_PATCH_DEPENDS("hknpMaterialPalette", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpShape", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpConstraintCollisionFilter", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpPairCollisionFilter")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpCollisionFilter", 0)
	HK_PATCH_DEPENDS("hknpPairCollisionFilter", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpCompressedMeshShapeTreeDataRun", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkcdStaticMeshTreeBasePrimitiveDataRunBasehknpCompressedMeshShapeTreeDataRunData")
	HK_PATCH_DEPENDS("hkcdStaticMeshTreeBasePrimitiveDataRunBasehknpCompressedMeshShapeTreeDataRunData", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpSurfaceVelocity", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpMaterialFactory", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpBinaryActionFactory", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpActionFactory")
	HK_PATCH_MEMBER_ADDED("actionTypeName", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("bodyAIdx", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("bodyBIdx", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpActionFactory", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpBoxVolumeComposer", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpBodiesComposer")
	HK_PATCH_MEMBER_ADDED("bodiesCount", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("volumeSize", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpBodiesComposer", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpBodyFactory", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("composer", TYPE_OBJECT, "hknpBodiesComposer", 0)
	HK_PATCH_MEMBER_ADDED("bodyInfo", TYPE_STRUCT, "hknpBodyCinfo", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpBodiesComposer", 0)
	HK_PATCH_DEPENDS("hknpBodyCinfo", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpBodyCinfoBase", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpDynamicBodyFactory", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpBodyFactory")
	HK_PATCH_MEMBER_ADDED("materialFactory", TYPE_OBJECT, "hknpMaterialFactory", 0)
	HK_PATCH_MEMBER_ADDED("motionInfo", TYPE_STRUCT, "hknpMotionCinfo", 0)
	HK_PATCH_DEPENDS("hknpBodyFactory", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpMotionCinfo", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpMaterialFactory", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpStaticBodyFactory", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpBodyFactory")
	HK_PATCH_MEMBER_ADDED("materialFactory", TYPE_OBJECT, "hknpMaterialFactory", 0)
	HK_PATCH_DEPENDS("hknpBodyFactory", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpMaterialFactory", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpWorldCinfo", 0)
	HK_PATCH_MEMBER_ADDED_VEC_4("gravity", 0.000000f,-9.810000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("broadPhaseMinExtent", -1000.000000f,-1000.000000f,-1000.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("broadPhaseMaxExtent", 1000.000000f,1000.000000f,1000.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_BYTE("enableRestitution", 1)
	HK_PATCH_MEMBER_ADDED_REAL("maxAllowedApproachingVelocityForHighQualitySolver", 0.100000f)
	HK_PATCH_MEMBER_ADDED("simulationType", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_INT("numSplitterCells", 16)
	HK_PATCH_MEMBER_ADDED_BYTE("solveActionsSingleThreaded", 1)
	HK_PATCH_MEMBER_ADDED_BYTE("enableDeactivation", 1)
	HK_PATCH_MEMBER_ADDED_BYTE("moveDeactivatedObjectsIntoStaticBroadPhase", 1)
	HK_PATCH_MEMBER_ADDED("leavingBroadPhaseBehavior", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_REAL("solverTau", 0.600000f)
	HK_PATCH_MEMBER_ADDED_REAL("solverDamp", 1.000000f)
	HK_PATCH_MEMBER_ADDED_INT("solverIterations", 4)
	HK_PATCH_MEMBER_ADDED_INT("solverMicrosteps", 1)
	HK_PATCH_MEMBER_ADDED_REAL("defaultSolverTimestep", 0.016667f)
	HK_PATCH_MEMBER_ADDED_BYTE("enableSolverDynamicScheduling", 0)
	HK_PATCH_MEMBER_ADDED_REAL("objectScale", 1.000000f)
	HK_PATCH_MEMBER_ADDED_INT("maxNumBodies", 4096)
	HK_PATCH_MEMBER_ADDED_INT("maxNumMotions", 0)
	HK_PATCH_MEMBER_ADDED_REAL("staticCollisionLookaheadDistance", 0.020000f)
	HK_PATCH_MEMBER_ADDED_INT("newPairCapacity", 131072)
	HK_PATCH_MEMBER_ADDED_INT("largeIslandSize", 100)
	HK_PATCH_MEMBER_ADDED_BYTE("mergeEventsBeforeDispatch", 1)
	HK_PATCH_MEMBER_ADDED_BYTE("enableRefCountedProperties", 0)
	HK_PATCH_MEMBER_ADDED_BYTE("consistencyChecksEnabled", 0)
	HK_PATCH_MEMBER_ADDED_POINTER("bodyBuffer", "hknpBody", 0)
	HK_PATCH_MEMBER_ADDED_POINTER("motionBuffer", "hknpMotion", 0)
	HK_PATCH_MEMBER_DEFAULT_SET_INT("simulationType", 1)
	HK_PATCH_MEMBER_DEFAULT_SET_INT("leavingBroadPhaseBehavior", 2)
	HK_PATCH_DEPENDS("hknpBody", 0)
	HK_PATCH_DEPENDS("hknpMotion", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpDetailedMaterialFactory", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpMaterialFactory")
	HK_PATCH_MEMBER_ADDED("info", TYPE_STRUCT, "hknpMaterialCinfo", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpMaterialCinfo", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpMaterial", 0)
	HK_PATCH_DEPENDS("hknpMaterialFactory", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpActionFactory", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpCapsuleShape", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpConvexShape")
	HK_PATCH_MEMBER_ADDED("a", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("b", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpConvexShape", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpShape", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpShapeMassDistribution", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("massDistribution", TYPE_STRUCT, "hkCompressedMassProperties", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkCompressedMassProperties", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpBodiesComposer", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpBodyCinfoBase", 0)
	HK_PATCH_MEMBER_ADDED("shape", TYPE_OBJECT, "hknpShape", 0)
	HK_PATCH_MEMBER_ADDED_INT("collisionFilterInfo", 0)
	HK_PATCH_MEMBER_ADDED_INT("modifierFlags", 0)
	HK_PATCH_MEMBER_ADDED("qualityType", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("qualityFlags", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("collisionLookAheadDistance", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_DEFAULT_SET_INT("qualityFlags", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpShape", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpSphereShape", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpConvexShape")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpConvexShape", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpShape", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpSimpleMaterialFactory", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpMaterialFactory")
	HK_PATCH_MEMBER_ADDED("friction", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("restitution", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpMaterialFactory", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpConstraintFactory", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpWorldSnapshot", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("worldCinfo", TYPE_STRUCT, "hknpWorldCinfo", 0)
	HK_PATCH_MEMBER_ADDED("bodies", TYPE_ARRAY_STRUCT, "hknpBody", 0)
	HK_PATCH_MEMBER_ADDED("motions", TYPE_ARRAY_STRUCT, "hknpMotion", 0)
	HK_PATCH_MEMBER_ADDED("motionProperties", TYPE_ARRAY_STRUCT, "hknpMotionProperties", 0)
	HK_PATCH_MEMBER_ADDED("materials", TYPE_ARRAY_STRUCT, "hknpMaterial", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpWorldCinfo", 0)
	HK_PATCH_DEPENDS("hknpBody", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpMotion", 0)
	HK_PATCH_DEPENDS("hknpMaterial", 0)
	HK_PATCH_DEPENDS("hknpMotionProperties", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpConvexShape", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpShape")
	HK_PATCH_MEMBER_ADDED("expansionRadius", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("verticesOffset", TYPE_ARRAY_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("planesOffset", TYPE_ARRAY_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("facesOffset", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("indicesOffset", TYPE_ARRAY_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pad", TYPE_TUPLE_BYTE, HK_NULL, 12)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpShape", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpBodyQualityFlags", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpSimpleDynamicBodyFactory", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hknpBodyFactory")
	HK_PATCH_MEMBER_ADDED("materialFactory", TYPE_OBJECT, "hknpMaterialFactory", 0)
	HK_PATCH_MEMBER_ADDED("mass", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hknpBodyFactory", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hknpMaterialFactory", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpMaterialPaletteRefMaterialCinfo", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpMaterialPalettePaletteMaterial", 0)
	HK_PATCH_MEMBER_ADDED("materialId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("materialCInfo", TYPE_OBJECT, "hknpMaterialPaletteRefMaterialCinfo", 0)
	HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hknpMaterialPaletteRefMaterialCinfo", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hknpMaterialPalette", 0)
	HK_PATCH_MEMBER_ADDED("materials", TYPE_ARRAY_STRUCT, "hknpMaterialPalettePaletteMaterial", 0)
	HK_PATCH_DEPENDS("hknpMaterialPalettePaletteMaterial", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkFreeListArrayhknpShapeInstancehkHandleshort32767hknpShapeInstanceIdDiscriminant16hknpShapeInstance", 0)
	HK_PATCH_MEMBER_ADDED("elements", TYPE_ARRAY_STRUCT, "hknpShapeInstance", 0)
	HK_PATCH_MEMBER_ADDED("firstFree", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hknpShapeInstance", 0)
HK_PATCH_END()

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20120831)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2012
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
